# Generated by Django 5.2.2 on 2025-06-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('student_id', models.CharField(max_length=250, unique=True)),
                ('fathers_name', models.CharField(max_length=250)),
                ('mothers_name', models.CharField(max_length=250)),
                ('dob', models.DateTimeField()),
                ('std', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII'), ('9', 'IX'), ('10', 'X')], default=None, max_length=4, null=True)),
            ],
            options={
                'verbose_name_plural': 'Student Details',
            },
        ),
    ]
